spring.application.name=DiamondsPricesApplication
server.port=8081

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=diamond-stream-group
spring.kafka.consumer.auto-offset-reset=earliest

app.kafka.topic=DiamondsPricePrediction
prediction.python.executable=python3
prediction.python.script-path=src/main/resources/scripts/diamond_predict.py
prediction.python.timeout-seconds=10

app.python.executable=C:\ProgramData\anaconda3\envs\SMPD\python.exe

